---
title:  "numpy ndarray stacking 과 splitting "
# categories:
#   - Blog
tags: [python, numpy]

# toc: true
# toc_sticky: true
# toc_label: "페이지 목차"
---

### 배열 준비

In [33]:
import numpy as np
import cv2

im_g = cv2.imread("smallgray.png", cv2.IMREAD_GRAYSCALE)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [43]:
im_g.shape

(3, 5)

### 배열을 가로로 결합: hstack
+ 결합할 배열의 행이 일치해야 한다
+ 열은 일치하지 않아도 된다

In [34]:
ims = np.hstack((im_g, im_g))
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [35]:
ims.shape

(3, 10)

In [46]:
ims = np.hstack((im_g, im_g, im_g))
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143, 187, 158, 104,
        121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147, 198, 125, 255,
        255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182, 209, 134, 255,
         97, 182]], dtype=uint8)

In [47]:
ims.shape

(3, 15)

### 배열을 세로로 결합: vstack
+ 결합할 배열의 열 개수가 일치해야 한다
+ 행 개수는 일치하지 않아도 된다

In [49]:
ims = np.vstack((im_g, im_g, im_g))
ims

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [50]:
ims.shape

(9, 5)

### 열로 분할하기: vsplit
+ 열 개수의 약수로만 분할 가능하다

In [55]:
lst = np.hsplit(ims, 5)
lst

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8),
 array([[158],
        [125],
        [134],
        [158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8),
 array([[104],
        [255],
        [255],
        [104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8),
 array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8),
 array([[143],
        [147],
        [182],
        [143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [57]:
lst[0].shape

(9, 1)

### 행으로 분할하기: vsplit
+ 행 개수의 약수로만 분할 가능하다

In [51]:
ims

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [52]:
ims.shape

(9, 5)

+ 9개 행을 3개로 분할하여 3개의 배열을 만든다

In [62]:
lst = np.vsplit(ims, 3)
lst

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

+ vsplit()의 리턴은 list

In [63]:
type(lst)

list

In [64]:
lst[0]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [65]:
lst[0].shape

(3, 5)