---
title:  "numpy 기초"
# categories:
#   - Blog
tags: [python, numpy]

# toc: true
# toc_sticky: true
# toc_label: "페이지 목차"
---

### arrange() 함수 동작

In [21]:
import numpy as np
n = np.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [18]:
np.arange(3.0)

array([0., 1., 2.])

In [19]:
np.arange(3,7)

array([3, 4, 5, 6])

In [20]:
np.arange(3,7,2)

array([3, 5])

In [3]:
type(n)

numpy.ndarray

### reshape() 함수
+ 배열의 차원을 변경

In [4]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [5]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

### asarray() 함수
+ 입력 데이터를 numpy.ndarray 형식으로 변환

In [6]:
m = np.asarray([[123,12,45,789], [12,78,963,54], [555,45,654,2]])
m

array([[123,  12,  45, 789],
       [ 12,  78, 963,  54],
       [555,  45, 654,   2]])

### opencv를 이용한 이미지 읽기

In [7]:
import cv2
im_g = cv2.imread("smallgray.png", cv2.IMREAD_GRAYSCALE)

In [8]:
type(im_g)

numpy.ndarray

In [9]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [10]:
im_g.shape

(3, 5)

In [11]:
im_g[2,4]

182

In [12]:
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [15]:
for i in im_g:
    for j in i:
        print(j)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [16]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [17]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [13]:
im_rgb = cv2.imread("smallgray.png", cv2.IMREAD_COLOR)
im_rgb

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

### 이미지 쓰기

In [14]:
cv2.imwrite("newsmallgray.png", im_g)

True